### ISSUE TITLE
500 error on setup

### ISSUE THREAD

**Issue by danielbachhuber** [doejo/vip-notify#1]
Thanks for writing this! Super helpful.

I get a 500 error though, exposed in the logs as:

```
2015-02-20T23:38:22.360800+00:00 app[web.1]: SlackNotify::Error - No hooks:
```

Here are my config details:

![image](https://cloud.githubusercontent.com/assets/36432/6311385/d26ecf84-b916-11e4-8eb8-5e747cbf1cc4.png)

I've tried both an API token and a webhook URL as `SLACK_TOKEN`, but neither work.

Any configuration pointers?

**Comment by sosedoff** [comment]
Uh, i'll have to look into this since i no longer use to tool. Which gitlab version are you on ?

**Comment by danielbachhuber** [comment]
> Which gitlab version are you on ?

I'm not using Gitlab? I've deployed to Heroku.

> Uh, i'll have to look into this since i no longer use to tool.

Did you replace it with something else?

**Comment by sosedoff** [comment]
Im sorry, i got confused with another project (https://github.com/doejo/gitlab-slack). 
I believe the issue might be with slack deprecating team/token, they now use just webhook url.
Need to confirm this.

**Comment by sosedoff** [comment]
@danielbachhuber i pushed a few fixes which includes upgrade to new slack webhook urls instead of separae team/token vars. Please give it a try.

**Comment by danielbachhuber** [comment]
I ended up writing a PHP script for this :/ Thanks for putting time towards the change though.
